### ISSUE TITLE
Build toolchain setup for embeddded devices

### ISSUE THREAD

**Issue by phanimahesh** [apinf/proxy42#3]
We want to run proxy42 on raspi and other embedded devices. We'll be using nerves-project for building firmwares.

The branch experiments/nerves has our current progress so far. We are looking to have automated firmware builds on headless servers by cross compiling to as many targets as we can.

Help wanted: It appears there are dependencies for nerves and friends which were undeclared in docs, and assumptions about the build environment that weren't fully obvious (to me). If anyone can help test things out, figure out hidden dependencies, or tweak scripts and get a docker based build setup, please comment below.

**Comment by sa1** [comment]
There is overlap with https://github.com/apinf/platform/issues/2882 which is now closed.

Things still left:
- [ ] Automated travis firmware builds, covered by #9
- [ ] Make the network setup more robust?
- [ ] Docker builds
