### ISSUE TITLE
[BUG]: Unable to pass-through request through proxy

### ISSUE THREAD

**Issue by fogfish** [apinf/proxy42#43]
The basic proxy workflow seems to be broken. Following the guide

1. Create developer 
2. Issue Key
3. Register API

```
curl -vvv -XPOST -H "Content-Type: application/json" -d \
   '{"hostname": "example.com", "servers" : ["http://example.com"],
      "frontend_prefix": "/awesome-api/",
      "backend_prefix": "/does-this-work/",
      "strategy": "random", "rate_limit": 43,
      "additional_headers" : "", "auth_config": "auth_key"
   }' http://localhost:4001/apis
``` 

4. Authorise developer to use api

```
curl -vvv -XPOST -H "Content-Type: application/json" \
   -d '{"developer_id": "...from 1...", "api_id": "...from 3..."}' localhost:4001/authorizations
```

5. Issue request

```
curl -vvv -H "Authorization: Bearer ...from 2..." -H "Host: example.com" http://localhost:8080/awesome-api/
```

Proxy responds with
```
> GET /awesome-api/ HTTP/1.1
> Host: example.com
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: Bearer 64042e62-a007-4cea-bde2-17dca8fdf2d0
>
< HTTP/1.1 403 Forbidden
< Connection: keep-alive
< Server: Cowboy
< Date: Sun, 14 Apr 2019 14:34:22 GMT
< Content-Length: 0
<
* Connection #0 to host localhost left intact
```

**Comment by fogfish** [comment]
@phanimahesh Do you have any feedback about it?

**Comment by phanimahesh** [comment]
It should work. We have a bash script that checks that it is working.

When I was working on it last, choosing the auth strategy was not possible from control api yet, we hard coded it to auth_key. It may have been accidentally changed to oauth. One of p42_req, p42_settings and p42_router will show what's wrong. I'll check and get back to you.

**Comment by phanimahesh** [comment]
Sorry, Documentation mismatch. Code expects auth_config to be a json object with strategy and config_id as parameters.

Try with `auth_config: {"strategy": "auth_key"}` instead.

Work was started on a plugin registry that allows using strategy name instead of module names, and supporting configurable options for strategies. This  is a result of that feature not being completed fully.

**Comment by phanimahesh** [comment]
On a sidenote, looks like we did complete that feature to select auth strategy. Have to verify it works though.

**Comment by fogfish** [comment]
No help is I change `auth_config`.

```
curl -vvv -XPOST -H "Content-Type: application/json" -d \
   '{"hostname": "example.com", "servers" : ["http://example.com"],
      "frontend_prefix": "/awesome-api/",
      "backend_prefix": "/does-this-work/",
      "strategy": "random", "rate_limit": 43,
      "additional_headers" : "", "auth_config": {"strategy": "auth_key"}
   }' http://localhost:4001/apis
```

Still give forbidden.

**Comment by fogfish** [comment]
I do have a bad news `apitest.sh` fails with same reason 

```
API_ID = 619e040f-1195-450d-a327-f10be5f785e4
DEVELOPER_ID = e1e36e0f-bed5-4253-9959-57899d9fe072
KEY = aa4e551d-e77d-4ebb-8aeb-15e6ecf5f28a
HTTP/1.1 201 Created
cache-control: max-age=0, private, must-revalidate
content-length: 23
date: Fri, 26 Apr 2019 13:10:07 GMT
server: Cowboy

"Authorization created"

HTTP/1.1 403 Forbidden
Connection: keep-alive
Content-Length: 0
Date: Fri, 26 Apr 2019 13:10:08 GMT
Server: Cowboy



[OK] Request Failed as Expected
[FAIL] Request Unexpectedly Forbidden
HTTP/1.1 204 No Content
cache-control: max-age=0, private, must-revalidate
content-length: 0
date: Fri, 26 Apr 2019 13:10:08 GMT
server: Cowboy



HTTP/1.1 500 Internal Server Error
content-length: 0
date: Fri, 26 Apr 2019 13:10:09 GMT
server: Cowboy
```

The proxy pass-through functionality is definitely not working yet.

**Comment by phanimahesh** [comment]
I'll check and get back to you tonight.

**Comment by phanimahesh** [comment]
Looks like I need to trace, will get back to you by tomorrow.

**Comment by sa1** [comment]
The apitest.sh fails iirc because deletion of a user is unimplemented. We need to think about how we handle a user’s keys when a user is deleted, and what kind of db structure and plugin architecture(since keys are a feature of the auth_key plugin) we need to have. We need to implement a generic way to notify plugins that a user is deleted and then the plugin can take any action needed. 

EDIT: I was talking about the last 500 response. I didn’t notice that another test fails.

**Comment by fogfish** [comment]
At this moment, I more concern about this error 

```
HTTP/1.1 403 Forbidden
Connection: keep-alive
Content-Length: 0
Date: Fri, 26 Apr 2019 13:10:08 GMT
Server: Cowboy
```

which is caused by

```
# Make Authorized call
if http --check-status GET $SERVER_URL:8080/1500/ Authorization:"Bearer $KEY" &> /dev/null; then
    echo "[OK] Authorization Passed!!!"
else
    case $? in
        3) echo "[FAIL] Unexpected Direction" ;;
        4) echo "[FAIL] Request Unexpectedly Forbidden" ;;
        5) echo "[FAIL] Unexpected Server Error" ;;
    esac
fi
```

I would really appreciate if we stop debating here and just accept a fact that proxy feature do not work. Unless you can demonstrate a working workflow.

**Comment by phanimahesh** [comment]
There's no debate. It is broken. We'll find and fix it.

**Comment by fogfish** [comment]
The reason of this behaviour is
https://github.com/apinf/proxy42/blob/experiments/vegur/apps/proxy42_core/src/proxy42_router.erl#L94

It fails with
```
{function_clause,
        [{p42_auth_key,get_config,
             [<<>>],
             [{file,"src/strategies/auth/p42_auth_key.erl"},{line,32}]},
         {p42_auth_key,auth,3,
             [{file,"src/strategies/auth/p42_auth_key.erl"},{line,37}]},
         {proxy42_router,auth,2,[{file,"src/proxy42_router.erl"},{line,96}]},
         {proxy42_authenticate_middleware,execute,2,
             [{file,"src/proxy42_authenticate_middleware.erl"},{line,16}]},
         {vegur_midjan_translator,run,2,
             [{file,"src/vegur_midjan_translator.erl"},{line,37}]},
         {midjan_core,run_decision,3,[{file,"src/midjan_core.erl"},{line,90}]},
         {midjan_core,execute,3,[{file,"src/midjan_core.erl"},{line,49}]},
         {vegur_midjan_middleware,execute,2,
             [{file,"src/vegur_midjan_middleware.erl"},{line,46}]}]}
```

**Comment by fogfish** [comment]
Yeah, PR #47 fixes the issue
